language: ruby
rvm:
  - 2.2

branches:
  except:
    - production

addons:
  postgresql: "9.4"

services:
  - redis-server

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database th_demo_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:migrate
  - rackup -s puma -E production
  - sleep 3

gemfile:
  - Gemfile

matrix:
  include:
    - rvm: 2.2.3
      gemfile: Gemfile5