version: "2"
services:
  app:
    build: .
    image: th_dummy:latest
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
  web:
    extends:
      service: app
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  runner:
    extends:
      service: app
    entrypoint: "/bin/bash"
    volumes_from:
      - data
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    volumes_from:
      - data
    ports:
      - "5432"
  data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
      - /bundle
